DROP TABLE IF EXISTS Chat CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS Osallistuminen CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS Keikka CASCADE;
DROP TABLE IF EXISTS Kohde CASCADE;
DROP TABLE IF EXISTS Osaaminen CASCADE;
DROP TABLE IF EXISTS Karhu CASCADE;
DROP TABLE IF EXISTS Rooli CASCADE;

